### ISSUE TITLE
Feature: 정보 등록 api 및 gathering 오류 해결

### ISSUE THREAD

**Issue by hyeonjaez** [TripInfoWeb/solitour-backend#123]
## 어떤 기능인가요?

정보 등록 api 및 gathering 오류 해결

정보 등록
- 정보 등록 dto 받아서 정보 등록 (dto 안에 썸네일 이미지 주소, 본문 이미지 주소들이 있다)

gathering 오류 해결
- gathering isDeleted 해결
- gathering 페이지네이션 했을때 모임 신청 수락 인원수 해결

S3Upload 
- imageResponse dto -> S3FileResponse 로 수정

## Todo

- [x] 정보 등록 dto 받아서 정보 등록 (dto 안에 썸네일 이미지 주소, 본문 이미지 주소들이 있다)
- [x] gathering isDeleted 해결
- [x] gathering 페이지네이션 했을때 모임 신청 수락 인원수 해결
- [x]  imageResponse dto -> S3FileResponse 로 수정
