### ISSUE TITLE
Feature: 모임 좋아요 기능 / 모임,정보 북마크, 좋아요 중복 체크 / 모임,정보 북마크,좋아요 예외, 상태 코드 처리 

### ISSUE THREAD

**Issue by Astin01** [TripInfoWeb/solitour-backend#142]
## 어떤 기능인가요?

모임 좋아요 기능 
모임,정보 북마크, 좋아요 중복 체크 
모임,정보 북마크,좋아요 예외시에 오류 반환하고 controller에서 crud 상태에 따라 맞는 코드 반환 

## Todo

- [x] 모임 좋아요 기능
- [x] 모임,정보 북마크, 좋아요 중복 체크 
- [x] 모임,정보 북마크,좋아요 예외, 상태 코드 처리
