### ISSUE TITLE
Feature: 회원 탈퇴 기능 향상

### ISSUE THREAD

**Issue by Astin01** [TripInfoWeb/solitour-backend#150]
## 어떤 기능인가요?

회원 탈퇴시 디폴트 프로필로 변경, s3에 저장된 유저 이미지 삭제, 유저 정보 null로 변경

## Todo

- [x] 회원 탈퇴시 디폴트 프로필로 변경 
- [x]  s3에 저장된 유저 이미지 삭제
- [x] 유저 정보 null로 변경
- [x] kakao로부터 받은 refresh 토큰으로 access token 재발급하여 회원탈퇴
- [ ] google로부터 받은 refresh 토큰으로 access token 재발급하여 회원탈퇴
