### ISSUE TITLE
Feature : 기프티콘 결제

### ISSUE THREAD

**Issue by Astin01** [TripInfoWeb/solitour-backend#230]
## 어떤 기능인가요?

유저가 포인트를 지불하면 기프티콘이 결제된다.
유저는 결제한 기프티콘을 마이페이지에서 확인하고 사용한 기프티콘은 사용완료 처리 할 수 있다.
유저가 기프티콘을 결제할 경우 관리자에게 알림이 간다. 

## Todo

- [ ] 유저가 포인트를 지불할 경우 기프티콘이 결제
- [ ] 마이페이지에서 결제한 기프티콘 확인
- [ ] 기프티콘 사용완료 처리 기능
- [ ] 기프티콘 결제 시에 관리자에게 알림
