### ISSUE TITLE
Docs : Issue 템플릿 추가

### ISSUE THREAD

**Issue by Astin01** [TripInfoWeb/solitour-backend#233]
## 도입 취지
현재 조직 내에서 feature, bug이외의 issue들의 사용량이 증가하였습니다. 이에 맞춰 해당 이슈들을 템플릿으로 만들려고 합니다

## 어떤 문서작업 인가요?

docs, refactor, release, test 이슈 템플릿 작성

## Todo

- [ ] docs 이슈 템플릿
- [ ] refactor 이슈 템플릿
- [ ] release 이슈 템플릿
- [ ] test 이슈 템플릿
