### ISSUE TITLE
Feature: 회원 닉네임,성별, 생년월일 수정 및 회원 탈퇴

### ISSUE THREAD

**Issue by Astin01** [TripInfoWeb/solitour-backend#62]
## 어떤 기능인가요?

회원 닉네임, 성별, 생년월일을 수정할 수 있는 기능과 oauth로 가입한 회원에 대한 탈퇴기능 

## Todo

- [x] 회원 닉네임 수정
- [x] 회원 성별 수정
- [x] 회원 생년월일 수정
- [x] 회원 탈퇴
