### ISSUE TITLE
Feature: TODO 백엔드 업무 현황 

### ISSUE THREAD

**Issue by hyeonjaez** [TripInfoWeb/solitour-backend#95]
### 정보
- 수정
- 좋아요 기능
- 북마크 기능
- 검색 기능
- 태그 검색 기능 
- 필터링 정렬 통합

### 모임
- 홈 모임 6개 조회
- 모임 삭제
- 좋아요 기능
- 북마크 기능
- 검색 기능
- 태그 검색 기능

### 마이페이지
- 내가 작성한 정보
- 내가 작성한 모임 
- 내가 신청한 모임 
- 정보 북마크
- 모임 북마크

--- 

### 정재현
- [x] 정보 - 수정
- [x] 모임 - 홈 모임 6개 조회
- [x] 모임 - 삭제 
- [x] 필터링 정렬 통합
- [x] 내가 신청한 모임 
- [x] 검색 기능 
- [x] 정보 등록할때 이미지 업로드 방식 수정

### 원동훈
- [x] 정보 좋아요 
- [x] 모임 좋아요
- [x] 태그 검색 기능
- [x] 내가 작성한 정보 
- [x] 내가 작성한 모임
- [x] 정보 북마크
- [x] 모임 북마크 
- [x] 이미지 업로드 S3 경로 컨벤션에 맞게 수정 

---

### S3 경로 컨벤션

- 서버이름/엔티티이름/{유저아이디}/파일명

ex)
dev/information/{id}/hihijiji
dev/diary/{id}/dhjijijiji
dev/user/{id}/hihihihi
prod/

**Comment by HyunJinNo** [comment]
현재 구현된 정보 북마크 기능에서 북마크 등록할 때는 정보 id값을 넘기는데, 북마크 취소할 때는 북마크 id값을 요구하네요. 북마크 id값을 클라이언트에서 알 수 있는 방법이 없을 것 같아서 북마크 취소할 때도 정보 id값을 넘기는 것이 맞지 않을까 생각합니다.
